### PR TITLE
Add a callback to the elastalert process to stop the node server on child exit

### PR DESCRIPTION
**Pull request by film42**
The node server spawns the python process, listens for error and exit events, but never uses these events to restart the python process or stop the node server. Since the node server will crash if it can't create an elasticsearch index, I think the server should also stop if the elastalert app exits.

Why this change? We have elastalert running in production using this docker container, and we'll randomly see the python process exit, but the node server (under docker) continues to run, silently failing, which means we start to miss alerts. By merging this change, we can at least ensure that the lifetime of the node server will never exceed the elastalert python app.

We certainly need to look deeper into what's causing the elastalert python app to fail, but that's a separate issue, in my opinion.

### CODE REVIEW

**Comment by ETetzlaff** [comment]
👍

**Comment by martijnrondeel** [comment]
Thank you for your contribution, this was a much requested feature. I've merged the changes into develop and will publish a new release today.

**Comment by martijnrondeel** [comment]
Now live in the latest [2.0.0 release](https://github.com/bitsensor/elastalert/releases/tag/2.0.0).

**Comment by film42** [comment]
Woo hoo! Thank you for the fast review @martijnrondeel !

**Pull request merged**
